name: "Compatibility Report"
description: Report a game's compatibility.
title: "[REPORT] - <Game Name Here>"
body:
  - type: dropdown
    id: system
    attributes:
      label: "System"
      description: What system is the game for?
      multiple: true
      options:
        - Game Boy
        - Game Boy Advance
        - Game Boy Color
    validations:
      required: true
  - type: dropdown
    id: region
    attributes:
      label: "Region"
      description: What is the game's region
      multiple: true
      options:
        - Japan
        - USA
        - Europe
        - Multi Region
        - World
        - Australia
        - Brazil
        - Canada
        - China
        - Denmark
        - France
        - Germany
        - Italy
        - Korea
        - Netherlands
        - Spain
        - Sweden
    validations:
      required: true
  - type: dropdown
    id: bios
    attributes:
      label: "BIOS"
      description: What BIOS did you test it on ?
      multiple: true
      options:
        - Open Source BIOS
        - Retail BIOS
    validations:
      required: true
  - type: dropdown
    id: condition
    attributes:
      label: "Condition"
      description: What is the game's condition?
      multiple: true
      options:
        - Broken
        - Boots to title
        - Playable with issues
        - Fully working
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Issues (if any)"
      description: Please describe any issues you encountered while testing
      placeholder: Any issues while testing...
    validations:
      required: true
